apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "php-fpm.fullname" . }}
  labels:
    {{- include "php-fpm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "php-fpm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "php-fpm.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: my-release-php-fpm
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: php-fpm
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: "/opt/bitnami/apps/wordpress/htdocs"
              name: pv-storage
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
