apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "php-fpm.fullname" . }}
  labels:
    type: local
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/florentpradier/Documents/Perso-Formation/Projects/data"