
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    app: {{ include "wordpress.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  nginx.conf: |-
    server {
      listen 0.0.0.0:80;
      root /opt/bitnami/apps/wordpress/htdocs;
      location / {
        index index.html index.php;
      }
      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass {{ .Release.Name }}-php-fpm:9000;
        fastcgi_index index.php;
        fastcgi_param  SCRIPT_FILENAME /opt/bitnami/apps/wordpress/htdocs$fastcgi_script_name;
      }
    }