apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-php-fpm
        - name: nginx-config
          configMap:
            name: {{ include "wordpress.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: WORDPRESS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: password
            - name: MARIADB_HOST
              value: "vtgate-service"
            - name: MARIADB_PORT_NUMBER
              value: "{{ .Values.database.dbport }}"
            - name: WORDPRESS_DATABASE_USER
              value: "{{ .Values.database.dbuser }}"
            - name: WORDPRESS_DATABASE_NAME
              value: "{{ .Values.database.dbname }}"
          volumeMounts:
            - mountPath: "/opt/bitnami/apps/wordpress/htdocs"
              name: pv-storage
            - name: nginx-config
              mountPath: /opt/bitnami/nginx/conf
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
